version: 2.1 
jobs:
  run-tests:
    docker:
      - image: salesforce/salesforcedx:latest-full
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "sfdx-project.json" }}
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: . build/install_dependencies.sh
      - save_cache:
          key: dependency-cache-{{ checksum "sfdx-project.json" }}
          paths:
            - node_modules
      - run: 
          name: Authenticate to Production
          command: . build/login_to_org.sh
workflows:
  version: 2
  validate:
    jobs:
      - run-tests