version: 2.1 
jobs:
  run-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "sfdx-project.json" }}
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: . build/install_dependencies.sh
      - save_cache:
          key: dependency-cache-{{ checksum "sfdx-project.json" }}
          paths:
            - node_modules
      - run: 
          name: Login to Org
          #command: . build/login_to_org.sh
          command: 
            openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
            openssl rsa -in assets/server.key -check -noout 
            sfdx force:auth:jwt:grant --clientid $APP_KEY --jwtkeyfile assets/server.key --username $SF_USERNAME --instanceurl $SFDX_PATH --setdefaultdevhubusername -a DevHub
            echo "Authenticated..."
workflows:
  version: 2
  validate:
    jobs:
      - run-tests