version: 2.1 
jobs:
  run-tests:
    docker:
      - image: salesforce/salesforcedx:latest-full
    steps:
      - checkout
      - run: 
          name: Authenticate to Production
          command: . build/login_to_org.sh
workflows:
  version: 2
  validate:
    jobs:
      - run-tests